spring:
  profiles:
    include: secret # application-secret.yml을 불러옵니다.
  application:
    name: ticketing-lab

  # MySQL 설정 (로컬 DB)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketing_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true

  # JPA / Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update # 개발 단계용 (추후 validate/none으로 전환)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100 # N+1 최적화용
    open-in-view: false # [성능 최적화] OSIV 비활성화: DB 커넥션을 트랜잭션(Service) 종료 시 즉시 반납하여 커넥션 고갈 방지

  # Redis 설정 (로컬 Redis)
  data:
    redis:
      host: localhost
      port: 6379

# JWT 커스텀 설정
jwt:
  access-token-expiration: 1800000   # 30분 (ms 단위)
  refresh-token-expiration: 604800000 # 7일 (ms 단위)